ARG BASE_IMAGE_NAME=debian
ARG BASE_IMAGE_TAG=unstable
ARG BASE_IMAGE_TAG_SUFFIX=-slim
FROM $BASE_IMAGE_NAME:$BASE_IMAGE_TAG$BASE_IMAGE_TAG_SUFFIX

ENV DEBIAN_PRIORITY=critical
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get upgrade -y

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  git \
  make \
  protobuf-compiler \
  golang-go \
  clang-format \
  npm

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
RUN go install github.com/bufbuild/buf/cmd/buf@latest
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
RUN go install github.com/segmentio/golines@latest
RUN go install mvdan.cc/gofumpt@latest

RUN npm install --save-dev --save-exact --global prettier

##############################################
# headscale build deps
# - https://github.com/juanfont/headscale?tab=readme-ov-file#testing-and-building
##############################################

# headscale repo: https://github.com/juanfont/headscale.git

ENV HEADSCALE_SRC="/src/headscale"

RUN mkdir -p "${HEADSCALE_SRC}"
RUN cd "${HEADSCALE_SRC}" \
  && git init \
  && git remote add origin "https://github.com/juanfont/headscale.git"

#########################
# repo metadata cleanup #
#########################

RUN apt-get update && apt-get upgrade -y
RUN apt autoremove --purge -y
RUN apt-get clean -y
RUN rm -rf /var/lib/apt/lists/*

###############
# environment #
###############

ENV OUT_DIR="/out"
RUN mkdir -p "${OUT_DIR}"

ENV PREFIX_DIR="/usr/local"

ARG IMAGE_ENV_ROOT="/srv"
RUN mkdir -p "${IMAGE_ENV_ROOT}"

ARG IMAGE_ETC_DIR="${IMAGE_ENV_ROOT}/etc"
RUN mkdir -p "${IMAGE_ETC_DIR}"

ARG IMAGE_ENV_DIR="${IMAGE_ENV_ROOT}/env"
RUN mkdir -p "${IMAGE_ENV_DIR}"

#############
# provision #
#############

ARG TMP_PROVISION_DIR="/tmp/.build-env-provision"
RUN mkdir -p "${TMP_PROVISION_DIR}"

#COPY import-profile "${IMAGE_ENV_DIR}/import-profile"

##############
# entrypoint #
##############

#ENTRYPOINT ["bash", "-o", "history"]
COPY entrypoint.sh "/srv/entrypoint.sh"
ENTRYPOINT "/srv/entrypoint.sh"

WORKDIR "/srv"
